CREATE DATABASE IF NOT EXISTS keep_mini;
USE keep_mini;

CREATE TABLE IF NOT EXISTS cards (
  id CHAR(36) PRIMARY KEY,
  type ENUM('note', 'task') NOT NULL DEFAULT 'note',
  title VARCHAR(80) NOT NULL,
  content VARCHAR(400) NOT NULL DEFAULT '',
  color VARCHAR(7) NOT NULL DEFAULT '#fff8b8',
  done TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
